Repository andersfylling/disgord, pull requests merged in 2019-09, with the labels that each got.

#192 auto release on milestone close
  .github/milestone-release.sh
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile
  cmd/docker/docker-compose.yaml
  cmd/docker/update.sh
Labels: enhancement

#199 fixes issue with identify for distributed bots doing sharding
  client.go
  event/events.go
  events.go
  events_gen.go
  reactor.go
  reactor_gen.go
  sort_gen.go
  websocket/sharding.go
Labels: bug

#204 rename ShardConfig.TotalNrOfShards to ShardConfig.ShardCount
  client.go
  websocket/sharding.go
  websocket/sharding_test.go
Labels: enhancement, type: refactor

#205 Feature/integration tests
  .github/workflows/integration-test.yml
  disgord.sh
  test/integration_gateway_test.go
Labels: enhancement

#203 Some grammar changes/fixes, more to come
  disgord.go
  docs/COMPARISON.md
  docs/TEMPLATE_BUG.md
  endpoint/guild.go
  event/events.go
  websocket/client.go
  websocket/packets.go
  websocket/queue.go
  websocket/websocket.go
Labels: documentation

#210 Use slice in Request Guild Members Command
  channel_test.go
  client.go
  cmd/docker/go.mod
  cmd/docker/go.sum
  commands.go
  events_gen.go
  gateway_commands.go
  generate/discorddocs/go.mod
  go.mod
  go.sum
  session.go
  sort_gen.go
  struct.go
  struct_test.go
  voiceconnection.go
  websocket/client.go
  websocket/eventclient.go
  websocket/eventclient_test.go
  websocket/oncemap.go
  websocket/opcode/opcodes.go
  websocket/packets.go
  websocket/queue.go
  websocket/queue_test.go
  websocket/sharding.go
  websocket/sharding_test.go
  websocket/util.go
  websocket/voiceclient.go
Labels: bug, enhancement

#218 Fix voice options not being used (self-mute & deafen)
  voiceconnection.go
Labels: enhancement
